mysql:
  restart: always
  image: mysql:latest
  environment:
    - MYSQL_USER=mattermost
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=mattermost
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /srv/docker/mattermost/mysql:/var/lib/mysql

mattermost:
  restart: always
  image: jostyee/docker-mattermost:5.0.0
  links:
    - mysql:mysql
  ports:
    - "8080:80"
  environment:
    - MM_SERVICESETTINGS_LISTENADDRESS=:80
    - MM_SERVICESETTINGS_ENABLECUSTOMEMOJI=true
    - MM_SERVICESETTINGS_ENABLELINKPREVIEWS=true
    - MM_EMAILSETTINGS_INVITESALT=long-and-random-alphanumeric-string
    - MM_FILESETTINGS_PUBLICLINKSALT=long-and-random-alphanumeric-string
    - MM_SQLSETTINGS_ATRESTENCRYPTKEY=long-and-random-alphanumeric-string
    - MM_SQLSETTINGS_DRIVERNAME=mysql
    - MM_SQLSETTINGS_DATASOURCE=user:passwd@tcp(host:port)/db?charset=utf8mb4,utf8%26readTimeout=30s%26writeTimeout=30s
  volumes:
    - /srv/docker/mattermost/mattermost:/mattermost/data
